# Spring Boot Database Configuration (Oracle DB)
spring.datasource.url=jdbc:oracle:thin:@//DESKTOP-GBL41N2:1521/orclpdb
spring.datasource.username=kins_user
spring.datasource.password=kins_user
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate/JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
