-- V2: Add premium and amount columns to POLICY table
ALTER TABLE POLICY ADD (
    SUM_ASSURED NUMBER(15, 2) DEFAULT 0,
    BASIC_PREMIUM NUMBER(12, 2) DEFAULT 0,
    ADDL_PREMIUM NUMBER(12, 2) DEFAULT 0,
    DISCOUNT NUMBER(12, 2) DEFAULT 0,
    LOADING NUMBER(12, 2) DEFAULT 0,
    CHARGES NUMBER(12, 2) DEFAULT 0
);
