-- V4: Create COMMON_CODE table
CREATE TABLE COMMON_CODE (
    cc_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cc_type VARCHAR2(50) NOT NULL,
    cc_type_desc VARCHAR2(200),
    cc_Code VARCHAR2(50) NOT NULL,
    cc_code_desc VARCHAR2(200),
    cc_show_yn NUMBER(1) DEFAULT 1,
    cc_value VARCHAR2(500),
    cc_created_date DATE DEFAULT SYSDATE,
    cc_created_by VARCHAR2(50),
    cc_modified_date DATE,
    cc_modified_by VARCHAR2(50),
    CONSTRAINT UNQ_CC_TYPE_CODE UNIQUE (cc_type, cc_Code)
);

CREATE INDEX IDX_CC_TYPE ON COMMON_CODE(cc_type);
